### ISSUE TITLE
Use turtle as master format

### ISSUE THREAD

**Issue by VladimirAlexiev** [Haigutus/Energy-Reference-Data#18]
May I strongly suggest that you use turtle as master format
- easier to read
- smaller
- can expose errors made in RDF XML, especially re `rdf:ID` that you use extensively but is obsolete because it's relative and calls for trouble when you don't specify `xml:base`

**Comment by Haigutus** [comment]
Thanks for the proposal

The short answer:
I am quite sure we will stay with RDF/XML for now and if any transition is to happen, it will be most likely to JSONLD.

Longer response to your reasons:
- easier to read: This is not objective as TSO community works daily with XML and a bit with JSON, the RDF/XML is much more readable and understandable than new unfamiliar format. For now XML is the most usable, readable and familiar serialisation format for our community. Longer term plans are being discussed about moving to JOSNLD but nothing has been agreed as functionalities supported for xml out of the box like XSLT, XSD and XPATH are not integral part of any other format. Thus while I see no move to use turtle as master format, we can for sure see that we convert and make available the data in turtle format.
- smaller: agree, but from my point of view on expense of readability and ease of use. Tooling availability both IDE-s and parsers is much smaller compared to XML and JSON.
- can expose errors made in RDF XML: do not agree, maybe I am not informed enough on turtle, but tooling available to work with turtle is very small compared to XML and JSON (editing, validating, parsing, serializing)
- rdf:ID is obsolete: agree, this should not be used, if you see that is used anywhere do please point it out

**Comment by Haigutus** [comment]
RDF/XML seems to be also the master format for EU Data Publication office

![image](https://user-images.githubusercontent.com/11408965/191602676-f9b26c53-f2fe-44ea-b9d5-1050098e68a1.png)


https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/access-right

**Comment by VladimirAlexiev** [comment]
Ok, how about producing all 3 formats? That's easy, I can make a PR for ttl with a Makefile. But rename the RDF folder to a better name.

You can't convince me that something shorter is harder to read than something twice older. 

Yes, the CIM community is used to RDF XML, and the non-standard parseType=statements,  and obsolete rdf:id, and temporary UUIDs, and relative URLs: all bad habits it'll have to get out of.

If "we're used to the old way" was a valid argument, Dvorak would never happen, and CIM would not be moving to JSON-LD, and we would not be working on YAML-LD (a better JSON-LD).

As for tooling 
- there's plenty of turtle tooling, maybe you don't know it. Eg autocompletion, syntax hiliting and intellisense with LSP, in VSCode and other editors. 
- JSON has a huge amount of tooling.
- XSLT is the wrong tool to handle RDF XML because the same RDF can be expressed with many different XMLs. Yes, CIM is careful to fix one particular form of XML, but that's not true for any RDF
- JSON-LD also has a great variety, but you fix it with the context and frame 

At least I'm happy that you accept the turtle examples I post here as readable.

**Comment by Haigutus** [comment]
Under generated data rdf/xml will be the master data (as stated before, this is most familiar/comfortable format for our community) and default redirect will be also to rdf/xml for now, but under published data (docs/) will be multiple formats, that can be accessed by defining the file type suffix (ContentType based logic is still under investigation, probably possible only with javascript run at client side)

json-ld added - http://energy.referencedata.eu/BaseVoltage/c8f7a2b8-a325-461f-a6d4-e74a1476ba2a.jsonld

turtle will be next to be added

**Comment by Haigutus** [comment]
Added turtle, example: - http://energy.referencedata.eu/BaseVoltage/c8f7a2b8-a325-461f-a6d4-e74a1476ba2a.ttl

Closing issue.
Resolution:
1. Master format will remain rdf/xml
2. Turtle (.ttl) format will be provided at publication
