### ISSUE TITLE
Create Concept Scheme for FaultCauseType

### ISSUE THREAD

**Issue by Haigutus** [Haigutus/Energy-Reference-Data#29]
@Pingviinituutti  to provide CIM input
@Haigutus to convert to SKOS

**Comment by Pingviinituutti** [comment]
Here it is! (Had to zip it because `XML` couldn't be uploaded directly.)

[PRA_faultCauseTypes_RD.zip](https://github.com/Haigutus/Energy-Reference-Data/files/10040360/PRA_faultCauseTypes_RD.zip)

**Comment by Haigutus** [comment]
@Pingviinituutti @Sveino @griddigit please test and review the first iteration

**Comment by Haigutus** [comment]
Ready for publication
