### ISSUE TITLE
Header aligned with DCAT and JSON-LD

### ISSUE THREAD

**Issue by Sveino** [Haigutus/Energy-Reference-Data#33]
We currently have the attributes:
- (add atttribute names)

In CIMJSON-LD the suggestion is to use:
```JSON
    "dcterms:temporal": {
        "@type": "http://purl.org/dc/terms/PeriodOfTime",
        "dcat:startDate": {
            "@value": "2022-03-30T23:00:00Z",
            "@type": "xsd:dateTime"
        }
    },
```
In CIMXML we should flatten the same attribute that belong to dcterms:teporal:

- dcat:startDate
- dcat:endData
This gives us a better alignment with CIMJSON-LD and it will be easier to understand. See more detail about the CIMJSON-LD header issue: https://github.com/digin-energi/Grunnprofil/issues/277

**Comment by griddigit** [comment]
On 10 Feb 2023, The group agrees to add
dcat:startDate
dcat:endDate

and delete time:hasXSDDuration and time:inXSDDateTimeStamp

the change will be done before 13 Feb and submitted with CIM EG with the package of NC v2.2 profiles.

**Comment by griddigit** [comment]
This was implemented in v66 of the master UML for NC prfofiles

**Comment by Haigutus** [comment]
CIM EG confirmed this approach with approval of METADATA AND DOCUMENT HEADERDATA EXCHANGE SPECIFICATION V2.2 on 2023-02-02. This document will be published on https://www.entsoe.eu/publications/electronic-data-interchange-edi-library/
