### ISSUE TITLE
FaultCauseType header changes

### ISSUE THREAD

**Issue by Haigutus** [Haigutus/Energy-Reference-Data#44]
Proposal to change:

1. descritpion: ENTSO-E Fault Cause Reference model -> Fault Cause Reference model
2. modelingAuthority: http://energy.referencedata.eu/Fault -> https://energy.referencedata.eu/FaultCauseType

Justification:

1. This is meant to be generic, both for TSO and DSO-s, thus ENTSO-E name in the description is not helping with that goal
2. This is the URL, where it is published and available

**Comment by Pingviinituutti** [comment]
A also changed the `dcat:keyword` to `GD`.
