### ISSUE TITLE
In a flat ConceptScheme should we use topConceptOf 

### ISSUE THREAD

**Issue by Sveino** [Haigutus/Energy-Reference-Data#50]
In [energy.referencedata.eu/PropertyReference.ttl](https://energy.referencedata.eu/PropertyReference.ttl) we include skos:topConceptOf "http://energy.referencedata.eu/PropertyReference" on all Concept. Do we need it?

https://www.w3.org/TR/skos-reference/#schemes

Example:
```
<A> rdf:type skos:Concept ;
  skos:prefLabel "love"@en ;
  skos:altLabel "adoration"@en ;
  skos:broader <B> ;
  skos:inScheme <S> .

<B> rdf:type skos:Concept ;
  skos:prefLabel "emotion"@en ;
  skos:altLabel "feeling"@en ;
  skos:topConceptOf <S> .

<S> rdf:type skos:ConceptScheme ;
  dct:title "My First Thesaurus" ;
  skos:hasTopConcept <B> .
```

**Comment by Haigutus** [comment]
This is legacy that came from EU Data Publication office tooling, that uses top concept to build tree structure in their tools.
Proposal to keep the practice.
