### ISSUE TITLE
Incorrect use of urn:eic

### ISSUE THREAD

**Issue by ERelAlg** [Haigutus/Energy-Reference-Data#57]
I got reported  an issue with [energy.referencedata.eu](https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fenergy.referencedata.eu%2F&data=05%7C02%7Ceduardo.relanoalgaba%40entsoe.eu%7C4a2f1bdfda9e451a142d08dc3381ee8a%7C7ffbeccf0c1b496c897889209c2d375d%7C0%7C0%7C638441880349405082%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=hcTnFXUtJaAFVLUK5jxJgwfkFn3n3aCV0FvK%2FMVFJhI%3D&reserved=0) in regards to use urn:eic<UUID> .

It must be an EIC code rather than UUID.
![image](https://github.com/Haigutus/Energy-Reference-Data/assets/124910674/e5e25f0b-d115-466c-99f7-861795fa1f70)

**Comment by Haigutus** [comment]
Issue fixed, thanks for reporting.
